include_directories(${CMAKE_CURRENT_SOURCE_DIR})
include_directories(${CMAKE_CURRENT_BINARY_DIR})
include_directories(${CMAKE_BINARY_DIR}/generated/)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-protocol)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-transport)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-computing)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-crypto)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-storage)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-helper)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-transport)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-crypto/sdk)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-transport/ppc-front)
include_directories(${CMAKE_CURRENT_SOURCE_DIR}/wedpr-transport/ppc-gateway)
include_directories(${PROTO_OUTPUT_PATH})

set(VCPKG_INCLUDE_PATH "${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/include")
include_directories(${VCPKG_INCLUDE_PATH})