include(ExternalProject)
include(GNUInstallDirs)

file(MAKE_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/deps/)
ExternalProject_Add(APSI
        PREFIX ${CMAKE_CURRENT_SOURCE_DIR}/deps
        GIT_REPOSITORY https://${URL_BASE}/WeDPR-Team/APSI.git
        GIT_TAG 7626026ec925e865a8e722251a71c9f167eb5fd2
        GIT_SHALLOW false
        BUILD_IN_SOURCE 1
        CMAKE_ARGS -DCMAKE_PREFIX_PATH=${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET} -DCMAKE_INSTALL_PREFIX=${CMAKE_SOURCE_DIR}/deps
        LOG_DOWNLOAD 0
        LOG_CONFIGURE 0
        LOG_BUILD 0
        LOG_INSTALL 0
        )

ExternalProject_Get_Property(APSI SOURCE_DIR)

set(APSI_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/deps/include/APSI-0.8)
set(APSI_LIBRARY_DIR ${CMAKE_SOURCE_DIR}/deps/${CMAKE_INSTALL_LIBDIR}/libapsi-0.8.a)
file(MAKE_DIRECTORY ${APSI_INCLUDE_DIR})  # Must exist.

add_library(apsi INTERFACE IMPORTED)
set_property(TARGET apsi PROPERTY INTERFACE_LINK_LIBRARIES ${APSI_LIBRARY_DIR})
set_property(TARGET apsi PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${APSI_INCLUDE_DIR})
add_dependencies(apsi APSI)
unset(SOURCE_DIR)
