#pragma once
#include "ppc-framework/Common.h"
#include <string.h>

namespace ppc::psi
{
#define ECDH_MULTI_LOG(LEVEL) BCOS_LOG(LEVEL) << LOG_BADGE("ECDH-MULTI-PSI")
#define ECDH_MASTER_LOG(LEVEL) BCOS_LOG(LEVEL) << LOG_BADGE("ECDH-MULTI-PSI-MASTER")
#define ECDH_PARTNER_LOG(LEVEL) BCOS_LOG(LEVEL) << LOG_BADGE("ECDH-MULTI-PSI-PARTNER")
#define ECDH_CAL_LOG(LEVEL) BCOS_LOG(LEVEL) << LOG_BADGE("ECDH-MULTI-PSI-CALCULATOR")

DERIVE_PPC_EXCEPTION(ECDHMULTIException);
enum class EcdhMultiPSIMessageType : uint8_t
{
    GENERATE_RANDOM_TO_PARTNER = 0x01,
    SEND_ENCRYPTED_SET_TO_MASTER_FROM_CALCULATOR = 0x02,
    SEND_ENCRYPTED_SET_TO_MASTER_FROM_PARTNER = 0x03,
    SEND_ENCRYPTED_SET_TO_CALCULATOR = 0x04,
    SEND_ENCRYPTED_INTERSECTION_SET_TO_CALCULATOR = 0x05,
    RETURN_ENCRYPTED_INTERSECTION_SET_FROM_CALCULATOR_TO_MASTER = 0x06,
    SYNC_FINAL_RESULT_TO_ALL = 0x07,
};
}  // namespace ppc::psi
