/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption */

#ifndef _Included_com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption
#define _Included_com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption
 * Method:    keyBytes
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption_keyBytes(
    JNIEnv*, jclass, jint, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption
 * Method:    generateKey
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption_generateKey(
    JNIEnv*, jclass, jint, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption
 * Method:    encrypt
 * Signature: (II[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption_encrypt(
    JNIEnv*, jclass, jint, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption
 * Method:    decrypt
 * Signature: (II[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_SymmetricEncryption_decrypt(
    JNIEnv*, jclass, jint, jint, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
