/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webank_wedpr_sdk_jni_homo_NativeIhc */

#ifndef _Included_com_webank_wedpr_sdk_jni_homo_NativeIhc
#define _Included_com_webank_wedpr_sdk_jni_homo_NativeIhc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeIhc
 * Method:    generateKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeIhc_generateKey(
    JNIEnv*, jclass, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeIhc
 * Method:    encrypt
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeIhc_encrypt(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeIhc
 * Method:    decrypt
 * Signature: ([B[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeIhc_decrypt(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeIhc
 * Method:    add
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeIhc_add(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeIhc
 * Method:    sub
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeIhc_sub(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeIhc
 * Method:    scalaMul
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeIhc_scalaMul(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
