/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webank_wedpr_sdk_jni_homo_NativePaillier */

#ifndef _Included_com_webank_wedpr_sdk_jni_homo_NativePaillier
#define _Included_com_webank_wedpr_sdk_jni_homo_NativePaillier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    maxPublicKeyBytes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_maxPublicKeyBytes(
    JNIEnv*, jclass, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    maxPrivateKeyBytes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_maxPrivateKeyBytes(
    JNIEnv*, jclass, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    maxCipherBytes
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_maxCipherBytes(
    JNIEnv*, jclass, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    keyBitsFromKeyPair
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_keyBitsFromKeyPair(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    keyBitsFromPublicKey
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_keyBitsFromPublicKey(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    generateKeyPair
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_generateKeyPair(
    JNIEnv*, jclass, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    loadKeyPair
 * Signature: ([B[B)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_loadKeyPair(
    JNIEnv*, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    freeKeyPair
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_freeKeyPair(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    loadPublicKey
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_loadPublicKey(
    JNIEnv*, jclass, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    freePublicKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_freePublicKey(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    loadPrivateKey
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_loadPrivateKey(
    JNIEnv*, jclass, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    freePrivateKey
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_freePrivateKey(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    getPublicKeyJniObject
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_getPublicKeyJniObject(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    getPublicKeyBytesFromKeyPair
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_getPublicKeyBytesFromKeyPair(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    getPrivateKeyBytesFromKeyPair
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_getPrivateKeyBytesFromKeyPair(
    JNIEnv*, jclass, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    encryptFast
 * Signature: ([BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_encryptFast(
    JNIEnv*, jclass, jbyteArray, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    encryptFastWithoutPrecompute
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_encryptFastWithoutPrecompute(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    encrypt
 * Signature: ([BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_encrypt(
    JNIEnv*, jclass, jbyteArray, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    encryptWithoutPrecompute
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_encryptWithoutPrecompute(
    JNIEnv*, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    decrypt
 * Signature: ([BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_decrypt(
    JNIEnv*, jclass, jbyteArray, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    decryptWithoutPrecompute
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_decryptWithoutPrecompute(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    add
 * Signature: ([B[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_add(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    addWithoutPrecompute
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_addWithoutPrecompute(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    sub
 * Signature: ([B[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_sub(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    subWithoutPrecompute
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_subWithoutPrecompute(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    scalaMul
 * Signature: ([B[BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_scalaMul(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jlong);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativePaillier
 * Method:    scalMulWithoutPrecompute
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_webank_wedpr_sdk_jni_homo_NativePaillier_scalaMulWithoutPrecompute(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
