/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc */

#ifndef _Included_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
#define _Included_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
 * Method:    generateKey
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc_generateKey(
    JNIEnv*, jclass, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
 * Method:    encrypt
 * Signature: (I[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc_encrypt(
    JNIEnv*, jclass, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
 * Method:    decrypt
 * Signature: (I[B[B)Lcom/webank/wedpr/sdk/jni/codec/FloatingPointNumber;
 */
JNIEXPORT jobject JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc_decrypt(
    JNIEnv*, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
 * Method:    add
 * Signature: (I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc_add(
    JNIEnv*, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
 * Method:    sub
 * Signature: (I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc_sub(
    JNIEnv*, jclass, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc
 * Method:    scalaMul
 * Signature: (I[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_homo_NativeFloatingIhc_scalaMul(
    JNIEnv*, jclass, jint, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
