/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webank_wedpr_sdk_jni_crypto_FastOre */

#ifndef _Included_com_webank_wedpr_sdk_jni_crypto_FastOre
#define _Included_com_webank_wedpr_sdk_jni_crypto_FastOre
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    keyBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_keyBytes(JNIEnv*, jclass);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    cipherSize
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_cipherSize(
    JNIEnv*, jclass, jlong, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    plainSize
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_plainSize(
    JNIEnv*, jclass, jlong, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    generateKey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_generateKey(
    JNIEnv*, jclass);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    encrypt4String
 * Signature: ([B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_encrypt4String(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    decrypt4String
 * Signature: ([B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_decrypt4String(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    encrypt4Integer
 * Signature: ([BJZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_encrypt4Integer(
    JNIEnv*, jclass, jbyteArray, jlong, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    decrypt4Integer
 * Signature: ([B[BZ)J
 */
JNIEXPORT jlong JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_decrypt4Integer(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    encrypt4Float
 * Signature: ([B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_encrypt4Float(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    decrypt4Float
 * Signature: ([B[BZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_decrypt4Float(
    JNIEnv*, jclass, jbyteArray, jbyteArray, jboolean);

/*
 * Class:     com_webank_wedpr_sdk_jni_crypto_FastOre
 * Method:    compare
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_com_webank_wedpr_sdk_jni_crypto_FastOre_compare(
    JNIEnv*, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
